import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

import { badGateway, notImplemented } from '@/lib/api/errors';
import { getEnv } from '@/lib/env';
import type { StorageDriver, StoredObject } from '@/lib/storage/contract';
import { encodeKeyPath, sha256Hex, signRequest } from '@/lib/storage/sigv4';

export * from '@/lib/storage/contract';

/**
 * Where uploaded files go, chosen by `FILE_STORAGE_DRIVER`.
 *
 * The same shape as every other integration in this codebase: `none` by default,
 * so a deployment that has not thought about file storage does not quietly start
 * writing photographs somewhere it will not find them again. Photos are the one
 * feature whose absence is invisible until someone needs the evidence.
 */

/** Disk. Correct on a long-lived host, wrong on a serverless one — see `create`. */
function localDriver(root: string): StorageDriver {
  const base = resolve(root);

  /**
   * Resolves a key under the root, and refuses anything that escapes it.
   *
   * Keys are generated by `storageKeyFor` and never contain `..`, so this should
   * be unreachable. It is here because "should be unreachable" is exactly what is
   * said about every path-traversal bug before it is found, and the check costs a
   * comparison.
   */
  function pathFor(key: string): string {
    const full = resolve(join(base, key));
    if (full !== base && !full.startsWith(base + sep)) {
      throw new Error(`Refusing a storage key that escapes the root: ${key}`);
    }
    return full;
  }

  return {
    name: 'local',

    async put(key, body) {
      const path = pathFor(key);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, body);
    },

    async get(key) {
      try {
        const body = await readFile(pathFor(key));
        // The recorded mime type lives on the File row, not on disk; the caller
        // supplies it. Returning it here keeps the contract uniform across drivers.
        return { body: new Uint8Array(body), mimeType: 'application/octet-stream' };
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw error;
      }
    },

    async delete(key) {
      await rm(pathFor(key), { force: true });
    },
  };
}

/** Anything that speaks S3: AWS, Cloudflare R2, Backblaze B2, MinIO. */
function s3Driver(config: {
  bucket: string;
  region: string;
  endpoint: string;
  accessKeyId: string;
  secretAccessKey: string;
}): StorageDriver {
  const endpoint = new URL(config.endpoint);

  /*
   * Path-style addressing (`https://host/bucket/key`) rather than virtual-hosted.
   * R2 and MinIO serve path-style; AWS supports both. One form that works
   * everywhere beats a form that is marginally more idiomatic on one provider.
   */
  function urlFor(key: string) {
    const path = `/${encodeKeyPath(config.bucket)}/${encodeKeyPath(key)}`;
    return { url: new URL(path, endpoint).toString(), path };
  }

  async function send(
    method: 'GET' | 'PUT' | 'DELETE',
    key: string,
    body?: Uint8Array,
    mimeType?: string,
  ): Promise<Response> {
    const { url, path } = urlFor(key);

    const headers = signRequest({
      method,
      host: endpoint.host,
      path,
      region: config.region,
      service: 's3',
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
      payloadHash: sha256Hex(body ?? new Uint8Array()),
      ...(mimeType ? { headers: { 'content-type': mimeType } } : {}),
    });

    return fetch(url, {
      method,
      headers,
      // `Uint8Array` is a valid BodyInit at runtime; the DOM lib types it as
      // ArrayBufferView over a generic buffer, which does not narrow on its own.
      ...(body ? { body: body as unknown as BodyInit } : {}),
      // A hung bucket must not hold a request open until the platform kills it.
      signal: AbortSignal.timeout(20_000),
    });
  }

  return {
    name: 's3',

    async put(key, body, mimeType) {
      const response = await send('PUT', key, body, mimeType);
      if (!response.ok) {
        // The body names the problem (wrong region, missing bucket, bad key) and
        // belongs in the server log, never in a response to the browser.
        const detail = await response.text().catch(() => '');
        throw badGateway(`Storage rejected the upload (${response.status}): ${detail.slice(0, 300)}`);
      }
    },

    async get(key) {
      const response = await send('GET', key);
      if (response.status === 404) return null;
      if (!response.ok) {
        throw badGateway(`Storage could not return the file (${response.status}).`);
      }

      return {
        body: new Uint8Array(await response.arrayBuffer()),
        mimeType: response.headers.get('content-type') ?? 'application/octet-stream',
      };
    },

    async delete(key) {
      const response = await send('DELETE', key);
      // 204 on success, 404 when it was already gone — both are the end state.
      if (!response.ok && response.status !== 404) {
        throw badGateway(`Storage could not delete the file (${response.status}).`);
      }
    },
  };
}

let cached: StorageDriver | null | undefined;

/**
 * The configured driver, or null when file storage is switched off.
 *
 * Null rather than a throwing stub, so callers decide what absence means: the
 * upload route refuses with a 501 that names the setting, while the job screen
 * simply does not offer the control.
 */
export function storage(): StorageDriver | null {
  if (cached !== undefined) return cached;

  const env = getEnv();

  if (env.FILE_STORAGE_DRIVER === 'local') {
    cached = localDriver(env.FILE_STORAGE_DIR);
    return cached;
  }

  if (env.FILE_STORAGE_DRIVER === 's3') {
    // Validated at boot (src/lib/env.ts), so reaching here without them is a bug
    // rather than a misconfiguration.
    cached = s3Driver({
      bucket: env.S3_BUCKET!,
      region: env.S3_REGION,
      endpoint: env.S3_ENDPOINT!,
      accessKeyId: env.S3_ACCESS_KEY_ID!,
      secretAccessKey: env.S3_SECRET_ACCESS_KEY!,
    });
    return cached;
  }

  cached = null;
  return cached;
}

/** True when this deployment can actually store a file. */
export function storageEnabled(): boolean {
  return storage() !== null;
}

/** The driver, or a 501 explaining which setting turns it on. */
export function requireStorage(): StorageDriver {
  const driver = storage();
  if (!driver) {
    throw notImplemented(
      'File storage is not configured on this deployment, so photos cannot be uploaded. Set FILE_STORAGE_DRIVER.',
    );
  }
  return driver;
}

export type { StoredObject };

/** Tests only: forget the memoised driver after changing the environment. */
export function resetStorageForTests(): void {
  cached = undefined;
}
